CREATE TABLE IF NOT EXISTS `up` (
  `NIF` varchar(14) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'IDENTIFICADOR.',
  `ID_ROL` int(11) NOT NULL COMMENT 'ROL',
  `NIF_RESP` varchar(9) CHARACTER SET utf8 COLLATE utf8_spanish_ci DEFAULT NULL,
  `ID_PAIS` varchar(2) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'PAIS',
  PRIMARY KEY (`NIF`),
  FOREIGN KEY `FK_UP_UP` (`NIF_RESP`) REFERENCES `up` (`NIF`) ON UPDATE CASCADE,
  FOREIGN KEY `FK_UP_ROL` (`ID_ROL`) REFERENCES `r` (`CODIGO`) ON UPDATE CASCADE,
  FOREIGN KEY `FK_UP_PAIS` (`ID_PAIS`) REFERENCES `p` (`CODIGO`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='TABLA QUE CONTIENE A LOS USUARIOS DEL SISTEMA';


CREATE TABLE IF NOT EXISTS `r` (
  `CODIGO` int(11) NOT NULL COMMENT 'IDENTIFICADOR',
  `DESCRIPCION` varchar(50) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'DESCRIPCION',
  PRIMARY KEY (`CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='CONTIENE LOS ROLESH ';

CREATE TABLE IF NOT EXISTS `p` (
  `CODIGO` varchar(2) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'IDENTIFICADOR DE PAIS',
  `DESCRIPCION` varchar(60) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'DESCRIPCION DEL PAIS',
  PRIMARY KEY (`CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='TABLA QUE CONTIENE A LOS DISTRIBUIDORES ASOCIADOS AL SISTEMA';

ALTER TABLE `up`
  ADD CONSTRAINT `FK_UP_PAIS` FOREIGN KEY (`ID_PAIS`) REFERENCES `p` (`CODIGO`) ON UPDATE CASCADE,
  ADD CONSTRAINT `FK_UP_ROL` FOREIGN KEY (`ID_ROL`) REFERENCES `r` (`CODIGO`) ON UPDATE CASCADE,
  ADD CONSTRAINT `FK_UP_UP` FOREIGN KEY (`NIF_RESP`) REFERENCES `up` (`NIF`) ON UPDATE CASCADE;